// react/src/pages/components/LoginBadge.tsx
import { useSession, useLogin, useLogout } from '@/model/session';



export default function LoginBadge() {
    const session = useSession();
    const logout = useLogout();
    const login = useLogin();

    return (
        <>
            { session.user ? 

            <div className="navbar-item" v-if="session.user">
                Welcome, { session.user.name }
                <a onClick={()=>{logout()}}>Logout</a>
            </div >
            :
            <div className="navbar-item" v-else>
                <p className="control">
                    <button className="button is-primary" onClick={()=>login()}>
                        <span className="icon">
                            <i className="fas fa-user"></i>
                        </span>
                        <strong>Login</strong>
                    </button>
                </p>
                <p className="control">
                    <button className="button is-info is-light">
                        <span className="icon">
                            <i className="fas fa-user-plus"></i>
                        </span>
                        <strong>Sign up</strong>
                    </button>
                </p>
            </div >
            }
        </>
    )
}

// client/src/components/LoginBadge.vue
<script setup lang="ts">
import { useSession, login } from '@/model/session';
import { ref } from 'vue';

const session = useSession();

</script>

<template>
    <div class="navbar-item" v-if="session.user">
        Welcome, {{ session.user.name }}
        (<a @click="session.user = null"> logout </a>)
    </div>

    <div class="navbar-item" v-else>
        <p class="control">
            <button class="button is-primary" @click="login">
                <span class="icon">
                    <i class="fas fa-user"></i>
                </span>
                <strong>Login</strong>
            </button>
        </p>
        <p class="control">
            <button class="button is-info is-light">
                <span class="icon">
                    <i class="fas fa-user-plus"></i>
                </span>
                <strong>Sign up</strong>
            </button>
        </p>
    </div>
</template>

<style scoped></style>
